---
abstract: 'templatize installation paths'
author:
  - 'The Smithsonian Astrophysical Observatory'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Copy::Recursive: 0
  File::Temp: 0
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-TemplateInstallPath
no_index:
  directory:
    - inc
    - t
resources:
  license: http://opensource.org/licenses/gpl-3.0.html
version: 0.03
